### ISSUE TITLE
Use Github Actions for deploying doc site on PR merge

### ISSUE THREAD

**Issue by coreyshirk** [sorry-cypress/sorry-cypress.dev#1]
Thoughts on using Github Actions for CI/CD? We could use this as a trial to eventually use in the other repos.

**Comment by coreyshirk** [comment]
Currently looking at [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) if we plan to deploy the doc site to Github pages

**Comment by agoldis** [comment]
@coreyshirk  thanks for suggesting to use gh-pages. 👍🏻 Please let me know if you need any help. The documentation uses https://docz.site and generates a static assets.

**Comment by agoldis** [comment]
Closed by #2
