### ISSUE TITLE
Improve minio documentation 

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress.dev#12]
Clarify MINIO_URL and MINIO_ENDPOINT meaning

**Comment by coristo** [comment]
So after i did spend some time to make it work this are my installation tips:
If you want to run sorry cypress with minio locally, simply use docker-compose.minio.yml like it's in docs.
But if you're looking for possibility to make it accessibly for other users:
1. Generate your own MINIO_ACCESS_KEY and MINIO_SECRET_KEY and change it in docker-compose.minio.yml
2. Change all 'localhost' directive to ip of machine where it's hosted.
3. Set MINIO_ENDPOINT as ip address e.g. `MINIO_ENDPOINT: '192.168.0.5'` and MINIO_URL the same ip with http ``MINIO_URL: 'http://192.168.0.5'`
4. Be carrefoul with ports, you can change dashboard port (in every place in docker-compose.minio.yml), but for example you cannot change port of minio container.

I think this information should be in docs ;)

**Comment by agoldis** [comment]
Thanks @pawel-zajac90 I have updated the documentation
